# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EducationManagementSystem' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

pod "AFNetworking"
  # Pods for EducationManagementSystem

  target 'EducationManagementSystemTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EducationManagementSystemUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
